### PR TITLE
add ansible required `FilterModule` class

### PR DESCRIPTION
**Pull request by charltonstanley**
added required class for ansible to recognize this as a filter, allowing
it to be used in playbooks.

### CODE REVIEW

**Comment by pedigreetechnologiesintegration** [comment]
https://pedigreetechnologies.tpondemand.com/entity/132693

**Review by calscoo — COMMENTED** [review]
FilterModule method looks good!

**Review by calscoo — COMMENTED** [review]
FilterModule method looks good!

**Review by calscoo — APPROVED** [review]
FilterModule method looks good!

**Pull request merged**
